### ISSUE TITLE
Error with Puppeteer executablePath

### ISSUE THREAD

**Issue by froi** [krismuniz/bori#1]
¡Caballo, esto se ve bien tripioso!

---

After following the instructions in the README I'm getting this error

```shell
❯ bori "Hello"
file:///Users/froi/workspace/bori/node_modules/puppeteer-core/lib/esm/puppeteer/util/assert.js:25
        throw new Error(message);
              ^

Error: An `executablePath` or `channel` must be specified for `puppeteer-core`
    at assert (file:///Users/froi/workspace/bori/node_modules/puppeteer-core/lib/esm/puppeteer/util/assert.js:25:15)
    at ChromeLauncher.launch (file:///Users/froi/workspace/bori/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:63:13)
    at async mapPrompt (file:///Users/froi/workspace/bori/build/modality/prompt.mjs:4:25)
    at async file:///Users/froi/workspace/bori/build/main.mjs:25:16

Node.js v19.2.0
```

I'm not familiar with Puppeteer but I'm assuming that [prompt.mts#L12](https://github.com/krismuniz/bori/blob/main/src/modality/prompt.mts#L12) is to blame since I do not have _process.env.CHROME_PATH_ defined in my env.

Maybe adding Chrome and the needed value for the environment variable as dependencies to the README would be enough?

**Comment by krismuniz** [comment]
Totalmente de acuerdo!

**Comment by froi** [comment]
Me acabo de dar cuenta del `.env.example`. Creo que si añades el rename del archivo, el añadir de los valores y colocar el requisito del OPEN_API_TOKEN, estaría más que bien.

Happy to make the PR if you want 😉

**Comment by krismuniz** [comment]
@froi mandé some changes upstream, dime qué te parecen. Always open for PRs too!

**Comment by froi** [comment]
Mano, good enough IMO. Closing this out 😉
